#!/bin/bash
echo Running $BASH_SOURCE
set | egrep GIT
echo PWD is $PWD

# Get the diff for REVISIONS
LOG=`git log -U0 --oneline -p ORIG_HEAD..HEAD REVISIONS`
[ -z "$LOG" ] && echo REVISIONS was NOT changed && exit 0

# Need to update/add/remove dependencies.
# Process the LOG output in a proper language

#echo $LOG | glock hook
glock hook <<< "$LOG"
